spring:
  application:
    name: eureka-lindj
server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://10.0.2.10:${server.port}/eureka/